class fastrun:
    customersignup="/customers_signup"
    customerdelete="/customers_delete"
    standardroom="/Standard-room"
    deluxeroom="/Deluxe-room"
    suite="/Suite"
    booking="/booking"
    customerdetail="/customers_details"
    standardbooking="/standard_booking"
    deluxebooking="/Deluxe_booking"
    suitebooking="/Suite"
    customerlogin="/customers_login"
